name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'  # Node.js 버전을 18로 변경

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
      env:
        CI: false

    - name: Set up Git user
      run: |
        git config --global user.name "Ellie Choi"
        git config --global user.email "ellie19981008@gmail.com"

    # - name: Deploy to GitHub Pages
    #   env:
    #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
    #   run: npm run deploy
-   name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./build
        user_name: 'Ellie Choi'
        user_email: 'ellie19981008@gmail.com'
    - name: Clean up
      run: rm -rf node_modules
